version: "3.9"

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=cheevopw
      - POSTGRES_DB=cheevos
      - POSTGRES_USER=cheevo
    # volumes:
      # - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5555:5432"
