version: "3.9"

services:
  testdb:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cheevos_test
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5555:5432"
  devdb:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cheevos_dev
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5558:5432"
